### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by m-kostrzewa** [m-kostrzewa/tree-diff#1]
- [ ] Github: get triggered by ngrok on any repo using webhooks
- [ ] Github: setup better auth scheme; maybe a separate user?
- [ ] Github: deploy somewhere
- [ ] Gerrit
- [ ] Use diff or something, because large trees will be unreadable
- [ ] Show side-by-side diff
